// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCN1Ff15lJ18ZzteKPOMrE9Nce62zlTo',
    appId: '1:804774487573:web:93dca1cfb0b4440e0f101c',
    messagingSenderId: '804774487573',
    projectId: 'postopcare-747ba',
    authDomain: 'postopcare-747ba.firebaseapp.com',
    storageBucket: 'postopcare-747ba.firebasestorage.app',
    measurementId: 'G-HZCY5S7VPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3rQCRNDZa0pm7Y-62oLtP47iwgAXlHE',
    appId: '1:804774487573:android:f6e44899cc7334170f101c',
    messagingSenderId: '804774487573',
    projectId: 'postopcare-747ba',
    storageBucket: 'postopcare-747ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVSvAeZcAHvCYLrzxwEV0aLgoVqjJ_Cs',
    appId: '1:804774487573:ios:3450253f720bc3c00f101c',
    messagingSenderId: '804774487573',
    projectId: 'postopcare-747ba',
    storageBucket: 'postopcare-747ba.firebasestorage.app',
    iosBundleId: 'com.example.postopcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpVSvAeZcAHvCYLrzxwEV0aLgoVqjJ_Cs',
    appId: '1:804774487573:ios:3450253f720bc3c00f101c',
    messagingSenderId: '804774487573',
    projectId: 'postopcare-747ba',
    storageBucket: 'postopcare-747ba.firebasestorage.app',
    iosBundleId: 'com.example.postopcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCCN1Ff15lJ18ZzteKPOMrE9Nce62zlTo',
    appId: '1:804774487573:web:feaa1bacee72c9e60f101c',
    messagingSenderId: '804774487573',
    projectId: 'postopcare-747ba',
    authDomain: 'postopcare-747ba.firebaseapp.com',
    storageBucket: 'postopcare-747ba.firebasestorage.app',
    measurementId: 'G-2J5MRWLGG3',
  );

}